SYS_PARM_FILTER = (
    'autocommit',
    'binlog_cache_size',
    'bulk_insert_buffer_size',
    'character_set_server',
    'tx_isolation',
    'tx_read_only',
    'sql_mode',
    # connection #
    'interactive_timeout',
    'wait_timeout',
    'lock_wait_timeout',
    'skip_name_resolve',
    'max_connections',
    'max_connect_errors',
    # table cache performance settings
    'table_open_cache',
    'table_definition_cache',
    'table_open_cache_instances',
    # performance settings
    'have_query_cache',
    'join_buffer_size',
    'key_buffer_size',
    'key_cache_age_threshold',
    'key_cache_block_size',
    'key_cache_division_limit',
    'large_pages',
    'locked_in_memory',
    'long_query_time',
    'max_allowed_packet',
    'max_binlog_size',
    'max_length_for_sort_data',
    'max_sort_length',
    'max_tmp_tables',
    'max_user_connections',
    'optimizer_prune_level',
    'optimizer_search_depth',
    'query_cache_size',
    'query_cache_type',
    'query_prealloc_size',
    'range_alloc_block_size',
    # session memory settings #
    'read_buffer_size',
    'read_rnd_buffer_size',
    'sort_buffer_size',
    'tmp_table_size',
    'join_buffer_size',
    'thread_cache_size',
    # log settings #
    'log_error',
    'slow_query_log',
    'slow_query_log_file',
    'log_queries_not_using_indexes',
    'log_slow_admin_statements',
    'log_slow_slave_statements',
    'log_throttle_queries_not_using_indexes',
    'expire_logs_days',
    'long_query_time',
    'min_examined_row_limit',
    'binlog_rows_query_log_events',
    'log_bin_trust_function_creators',
    'expire_logs_days',
    'log_slave_updates',
    # innodb settings #
    'innodb_page_size',
    'innodb_buffer_pool_size',
    'innodb_buffer_pool_instances',
    'innodb_buffer_pool_chunk_size',
    'innodb_buffer_pool_load_at_startup',
    'innodb_buffer_pool_dump_at_shutdown',
    'innodb_lru_scan_depth',
    'innodb_lock_wait_timeout',
    'innodb_io_capacity',
    'innodb_io_capacity_max',
    'innodb_flush_method',
    'innodb_file_format',
    'innodb_file_format_max',
    'innodb_undo_logs',
    'innodb_undo_tablespaces',
    'innodb_flush_neighbors',
    'innodb_log_file_size',
    'innodb_log_files_in_group',
    'innodb_log_buffer_size',
    'innodb_purge_threads',
    'innodb_large_prefix',
    'innodb_thread_concurrency',
    'innodb_print_all_deadlocks',
    'innodb_strict_mode',
    'innodb_sort_buffer_size',
    'innodb_write_io_threads',
    'innodb_read_io_threads',
    'innodb_file_per_table',
    'innodb_stats_persistent_sample_pages',
    'innodb_autoinc_lock_mode',
    'innodb_online_alter_log_max_size',
    'innodb_open_files',
    'innodb_flush_log_at_trx_commit',
    # replication settings #
    'master_info_repository',
    'relay_log_info_repository',
    'sync_binlog',
    'gtid_mode',
    'enforce_gtid_consistency',
    'log_slave_updates',
    'binlog_format',
    'binlog_rows_query_log_events',
    'binlog_row_image',
    'relay_log',
    'relay_log_recovery',
    'slave_skip_errors',
    'slave_rows_search_algorithms',
    # semi sync replication settings #
    'plugin_load',
    'rpl_semi_sync_master_enabled',
    'rpl_semi_sync_master_timeout',
    'rpl_semi_sync_slave_enabled',
    # password plugin #
    'validate_password_policy',
    'validate_password',
    # metalock performance settings
    'metadata_locks_hash_instances',
    # new innodb settings #
    'loose_innodb_numa_interleave',
    'innodb_buffer_pool_dump_pct',
    'innodb_page_cleaners',
    'innodb_undo_log_truncate',
    'innodb_max_undo_log_size',
    'innodb_purge_rseg_truncate_frequency',
    # new replication settings #
    'slave_parallel_type',
    'slave_parallel_workers',
    'slave_preserve_commit_order',
    'slave_transaction_retries',
    # other change settings #
    'binlog_gtid_simple_recovery',
    'log_timestamps',
    'show_compatibility_56'
)

